name: groqhealth_biomarkers
description: Groqhealth biomarkers UI components.
version: 4.2.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  assets:
    - resources/images/
    - resources/images/quantiome_icon_android.png
  fonts:
    - family: avenirRoman
      fonts:
        - asset: resources/fonts/avenir_roman.ttf

    - family: avenirMedium
      fonts:
        - asset: resources/fonts/avenir_medium.ttf

    - family: avenirBook
      fonts:
        - asset: resources/fonts/avenir_book.ttf

    - family: LoraMedium
      fonts:
        - asset: resources/fonts/lora_medium.ttf